fint:
  metamodel:
    format: "-"
  kafka:
    application-id: fint-core-autorelation

spring:
  kafka:
    consumer:
      group-id: ${fint.kafka.application-id}

logging:
  level:
    no.fintlabs.kafka: OFF
    org.apache.kafka: OFF